spring:
  application:
    name: farmatodo-challenge
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shop}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.jdbc.lob.non_contextual_creation: true
  sql:
    init:
      mode: always
      platform: postgresql
  mail:
    host: ${SPRING_MAIL_HOST:localhost}
    port: ${SPRING_MAIL_PORT:1025}
    username: ${SPRING_MAIL_USR:USER}
    password: ${SPRING_MAIL_PWS:123}
    properties:
      mail.smtp.auth: ${SPRING_MAIL_SMTP_AUTH:false}
      mail.smtp.starttls.enable: ${SPRING_MAIL_STARTTLS_ENABLE:false}

app:
  security:
    apiKeyHeader: X-API-KEY
    allowedApiKeys: dev-123456
  tokenization:
    aesKey: 0123456789abcdef0123456789abcdef
  payment:
    approvalRate: 0.8
    maxRetries: 3
