spring:
  application:
    name: farmatodo-challenge
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.format_sql: false
      hibernate.show_sql: false
  sql:
    init:
      mode: always
      platform: postgresql
  logging:
    level:
      root: INFO
    file:
      name: /var/log/farmatodo-challenge.log
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USR}
    password: ${SPRING_MAIL_PWS}
    properties:
      mail.smtp.auth: ${SPRING_MAIL_SMTP_AUTH}
      mail.smtp.starttls.enable: ${SPRING_MAIL_STARTTLS_ENABLE}

app:
  security:
    apiKeyHeader: ${APP_API_KEY_HEADER}
    allowedApiKeys: ${APP_ALLOWED_APP_KEY}
  tokenization:
    aesKey: ${APP_TOKENIZATION_AESKEY}
  payment:
    approvalRate: ${APP_PAYMENT_APPROVALRATE}
    maxRetries: ${APP_PAYMENT_MAXRETRIES}