spring:
  application:
    name: farmatodo-challenge
  profiles:
    active: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shop}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.format_sql: true
      hibernate.show_sql: true
  sql:
    init:
      mode: always
      platform: postgresql
  logging:
    level:
      root: DEBUG
      org.springframework.web: DEBUG
  mail:
    host: ${SPRING_MAIL_HOST:localhost}
    port: ${SPRING_MAIL_PORT:1025}
    username: ${SPRING_MAIL_USR:USER}
    password: ${SPRING_MAIL_PWS:123}
    properties:
      mail.smtp.auth: ${SPRING_MAIL_SMTP_AUTH:false}
      mail.smtp.starttls.enable: ${SPRING_MAIL_STARTTLS_ENABLE:false}

app:
  security:
    apiKeyHeader: ${APP_API_KEY_HEADER:X-API-KEY}
    allowedApiKeys: ${APP_ALLOWED_APP_KEY:dev-123456}
  tokenization:
    aesKey: ${APP_TOKENIZATION_AESKEY:0123456789abcdef0123456789abcdef}
  payment:
    approvalRate: ${APP_PAYMENT_APPROVALRATE:0.8}
    maxRetries: ${APP_PAYMENT_MAXRETRIES:3}
